apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external-service
subsets:
  - addresses:
      - ip: 10.187.115.2
    ports:
      - port: 3306