apiVersion: v1
kind: Service
metadata:
  name: qna-app-sec-test
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app-sec-test: qna-app-sec-test
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-app-sec-test
  labels:
    app-sec-test: qna-app-sec-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app-sec-test: qna-app-sec-test
  template:
    metadata:
      labels:
        app-sec-test: qna-app-sec-test
    spec:
      containers:
        - name: qna-app-sec-test
          image: marthenl/qna-app-for-mysql-db:2.3.1.1
          ports:
            - containerPort: 8080
